CREATE TABLE uni (
    uni_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    uni_name VARCHAR2(20) NOT NULL,
    creation_date timestamp,
    CONSTRAINT uni_id_pk PRIMARY KEY (uni_id)
);
/
CREATE TABLE groups (
    gr_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    gr_name VARCHAR2(20) NOT NULL,
    uni_id NUMBER NOT NULL,
    creation_date timestamp,
    CONSTRAINT gr_id_pk PRIMARY KEY (gr_id)
);
/
CREATE TABLE students (
    st_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    st_name VARCHAR2(20) NOT NULL,
    gr_id NUMBER NOT NULL,
    enter_date timestamp,
    CONSTRAINT st_id_pk PRIMARY KEY (st_id)
);
/