blank_issues_enabled: true
contact_links:
  - name: '💬 General Questions'
    url: https://github.com/sMkTools/sMkTaskManager/discussions/new/choose
    about: Have a question? Start a new discussion.
