DROP TABLE log_students;
CREATE TABLE log_students (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    action VARCHAR2(10), 
    student_id NUMBER,
    student_name VARCHAR2(100),
    group_id NUMBER, 
    timestamp TIMESTAMP
);

SELECT * FROM log_students;

-- DROP TRIGGER log_students_tr;
CREATE OR REPLACE TRIGGER log_students_tr
AFTER INSERT OR UPDATE OR DELETE ON students
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        INSERT INTO log_students
        VALUES (NULL, 'INSERT', :NEW.id, :NEW.name, :NEW.group_id, SYSTIMESTAMP);
    ELSIF UPDATING THEN
        INSERT INTO log_students
        VALUES (NULL, 'UPDATE', :NEW.id, :NEW.name, :NEW.group_id, SYSTIMESTAMP);
    ELSIF DELETING THEN
        INSERT INTO log_students
        VALUES (NULL, 'DELETE', :OLD.id, :OLD.name, :OLD.group_id, SYSTIMESTAMP);
    END IF;
END;
/



